import { createFileRoute, Link } from "@tanstack/react-router";
import { Mail, FileText, ListTodo, Search, MessageSquare, ArrowRight, Sparkles } from "lucide-react";
import { Card } from "@/components/ui/card";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "AI Workplace Productivity Assistant" },
      { name: "description", content: "Automate emails, meeting notes, planning, research, and more with AI." },
      { property: "og:title", content: "AI Workplace Productivity Assistant" },
      { property: "og:description", content: "Automate emails, meeting notes, planning, research, and more with AI." },
    ],
  }),
  component: Dashboard,
});

const tools = [
  { to: "/email", title: "Smart Email Generator", desc: "Draft professional emails in seconds.", icon: Mail },
  { to: "/meetings", title: "Meeting Notes Summarizer", desc: "Turn transcripts into clear summaries.", icon: FileText },
  { to: "/tasks", title: "AI Task Planner", desc: "Break goals into actionable plans.", icon: ListTodo },
  { to: "/research", title: "AI Research Assistant", desc: "Get briefings on any topic.", icon: Search },
  { to: "/chat", title: "AI Chatbot", desc: "Conversational assistant for anything.", icon: MessageSquare },
];

function Dashboard() {
  return (
    <div className="space-y-8">
      <section className="rounded-2xl p-8 lg:p-10 text-primary-foreground relative overflow-hidden" style={{ background: "var(--gradient-primary)", boxShadow: "var(--shadow-elegant)" }}>
        <div className="flex items-center gap-2 text-xs font-medium opacity-90 mb-3">
          <Sparkles className="h-3.5 w-3.5" /> AI Workplace
        </div>
        <h1 className="text-3xl lg:text-4xl font-semibold tracking-tight max-w-2xl">
          Your AI-powered productivity copilot.
        </h1>
        <p className="mt-3 max-w-xl opacity-90">
          Five purpose-built tools to handle the busywork — so you can focus on what matters.
        </p>
      </section>

      <div>
        <h2 className="text-lg font-semibold mb-4">Tools</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {tools.map((t) => {
            const Icon = t.icon;
            return (
              <Link key={t.to} to={t.to} className="group">
                <Card className="p-5 h-full transition-all hover:-translate-y-0.5 hover:border-primary/40" style={{ boxShadow: "var(--shadow-soft)" }}>
                  <div className="h-10 w-10 rounded-lg flex items-center justify-center mb-4 bg-accent text-accent-foreground">
                    <Icon className="h-5 w-5" />
                  </div>
                  <h3 className="font-semibold">{t.title}</h3>
                  <p className="text-sm text-muted-foreground mt-1">{t.desc}</p>
                  <div className="mt-4 flex items-center text-sm text-primary font-medium">
                    Open <ArrowRight className="h-3.5 w-3.5 ml-1 transition-transform group-hover:translate-x-0.5" />
                  </div>
                </Card>
              </Link>
            );
          })}
        </div>
      </div>

      <Card className="p-5 border-dashed bg-muted/40">
        <p className="text-sm text-muted-foreground">
          <strong className="text-foreground">Responsible AI:</strong> Outputs are generated by AI and may contain inaccuracies or biased content. Always review and edit before sharing externally, and avoid entering confidential information.
        </p>
      </Card>
    </div>
  );
}
